export const ASSESSMENTS = {
  GET: 'GET_ASSESSMENTS',
  SAVE: 'SAVE_ASSESSMENTS',
  REMOVE: 'REMOVE_ASSESSMENTS',
  UPDATE: 'UPDATE_ASSESSMENTS',
};

export const BASE_URL = process.env.VUE_APP_API_URL;
